name: countries_app
description: A Flutter mobile app to browse, search, and favorite countries using REST Countries API
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3

  # Network
  dio: ^5.4.0
  dio_cache_interceptor: ^3.4.4
  dio_cache_interceptor_hive_store: ^3.1.1
  path_provider: ^2.1.1

  # Dependency Injection
  get_it: ^7.6.4

  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # Utilities
  intl: ^0.19.0
  shimmer: ^3.0.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

