name: countries_app
description: A Flutter mobile app to browse, search, and favorite countries using REST Countries API
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3

  # Network
  dio: ^5.4.0

  # Utilities
  intl: ^0.19.0
  shimmer: ^3.0.0

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

